namespace ControlServer.Infrastructure.Persistence;

/// <summary>
/// One administrator's declaration that the slot a vehicle is waiting on is faulty (REQ-0359, control-server#383), and what
/// the vehicle made of it.
/// </summary>
/// <remarks>
/// <para>
/// <b>The row is the audit record.</b> Every item REQ-0359 asks the server to audit is a column here, written once: who
/// declared, in which role, when, on which vehicle, demand, attempt and slot, under which fault category and note, the
/// readings the vehicle had last reported for that slot, and the vehicle's answer. The request columns are set when the row
/// is inserted and never touched again; the result columns are set once, by the first <c>SlotFaultDeclarationResult</c> for
/// the declaration, and a resent result changes nothing. The configuration-governance audit
/// (<c>AdministratorAuditRecordRow</c>) was not used: its object model is a governed configuration and its version, and a
/// declaration is neither. This follows the recovery session and the RIoT command audit, which are their own records too.
/// </para>
/// <para>
/// <b>At most one pending declaration per slot operation attempt</b>, enforced by a unique index filtered on
/// <see cref="State"/> = <see cref="SlotFaultDeclarationStates.Pending"/>: two administrators declaring the same slot at
/// the same moment both pass every read, and the second insert is what fails. Once the vehicle has answered, the attempt
/// can take another declaration, which is how a later slot of the same operation can still be declared after an earlier
/// one was refused because it closed.
/// </para>
/// </remarks>
public sealed class SlotFaultDeclarationRow
{
    /// <summary>The declaration's stable identity, generated by the server and sent as <c>declarationId</c>.</summary>
    public required string DeclarationId { get; set; }

    /// <summary>The caller's idempotency key: the same request sent again is answered from this row.</summary>
    public required string RequestId { get; set; }

    /// <summary>SHA-256 of the request's content, so a request id reused for another request is refused.</summary>
    public required string RequestContentHash { get; set; }

    public required string AgvId { get; set; }
    public required string DemandId { get; set; }
    public required string SlotOperationAttemptId { get; set; }

    /// <summary><c>LOAD</c> or <c>UNLOAD</c>: the operation the declared slot belonged to.</summary>
    public required string OperationType { get; set; }

    public int SlotNo { get; set; }

    /// <summary><c>LOCK</c>, <c>LIGHT_CURTAIN</c>, <c>DOOR_MECHANISM</c> or <c>IO_MODULE</c>.</summary>
    public required string FaultCategory { get; set; }

    public required string Note { get; set; }
    public required string AdministratorId { get; set; }

    /// <summary><c>MAINTENANCE_ADMINISTRATOR</c> or <c>SYSTEM_ADMINISTRATOR</c>, as claimed with the shared credential.</summary>
    public required string AdministratorRole { get; set; }

    public DateTimeOffset DeclaredAt { get; set; }

    /// <summary>
    /// The slot's lock, light curtain and unlock output from the vehicle's latest <c>SafetyStateSnapshot</c> of the session
    /// at the moment of declaring, with the time the vehicle observed them; null when the vehicle had reported none.
    /// </summary>
    public string? ReadingsJson { get; set; }

    /// <summary>The <c>SlotFaultDeclarationCommand</c> in the outbox, written in the same save as this row.</summary>
    public required string CommandMessageId { get; set; }

    /// <summary><see cref="SlotFaultDeclarationStates"/>.</summary>
    public required string State { get; set; }

    public string? ResultMessageId { get; set; }

    /// <summary><c>APPLIED</c> or <c>NOT_APPLICABLE</c>, as the vehicle reported it.</summary>
    public string? ResultOutcome { get; set; }

    /// <summary>
    /// The vehicle's <c>problem</c> when it refused the declaration; for an <see cref="SlotFaultDeclarationStates.Unreconciled"/>
    /// one, the problem of the <c>ProtocolProblem</c> it refused the replayed command with (and <see cref="ResultMessageId"/>
    /// is that message, <see cref="ResultOutcome"/> null); null otherwise.
    /// </summary>
    public string? ResultProblemJson { get; set; }

    public DateTimeOffset? ResultReceivedAt { get; set; }
}

/// <summary>The four states of a <see cref="SlotFaultDeclarationRow"/>.</summary>
public static class SlotFaultDeclarationStates
{
    /// <summary>Persisted and queued for the vehicle; the vehicle has not answered.</summary>
    public const string Pending = "PENDING";

    /// <summary>The vehicle stopped the operation and reports the slot <c>UNKNOWN</c> in its <c>OperationResult</c>.</summary>
    public const string Applied = "APPLIED";

    /// <summary>The vehicle refused it: the slot had closed, was already <c>UNKNOWN</c>, or the attempt had changed.</summary>
    public const string NotApplicable = "NOT_APPLICABLE";

    /// <summary>
    /// The vehicle gave its answer up (control-server#481): the server refused that answer for good, and the vehicle refused
    /// the replayed command with <c>SLOT_OPERATION_CONFLICT</c>. Nobody knows what the vehicle made of the declaration, so it
    /// is held to what an applied one holds back (a load cancellation of the attempt), and the attempt can be declared again.
    /// </summary>
    public const string Unreconciled = "UNRECONCILED";
}
