// <auto-generated />
using System;
using ControlServer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlServer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ControlServerDbContext))]
    [Migration("20260826071119_DurableOnboardBusinessInbox")]
    partial class DurableOnboardBusinessInbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.AcceptedDemandRow", b =>
                {
                    b.Property<string>("DemandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CatalogRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DemandRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HistoryEpoch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportDemandKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DemandId");

                    b.HasIndex("TransportDemandKey")
                        .IsUnique();

                    b.ToTable("AcceptedDemands");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.ConnectionRecoveryRow", b =>
                {
                    b.Property<string>("AgvId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveUnlockSetJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ResumeAuthorized")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SessionGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AgvId");

                    b.ToTable("ConnectionRecoveries");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.OperationResultRow", b =>
                {
                    b.Property<string>("ResultId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgvId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HistoricalOnly")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotOperationAttemptId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ResultId");

                    b.HasIndex("SlotOperationAttemptId", "ForcedRecoveryGeneration")
                        .IsUnique();

                    b.ToTable("OperationResults");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.OrderIntentRow", b =>
                {
                    b.Property<string>("MovementLegId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AgvLifecycleGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationStationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DispatchGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetStationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpperId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovementLegId");

                    b.HasIndex("UpperId")
                        .IsUnique();

                    b.ToTable("OrderIntents");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.ProtocolInboxRow", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("ProtocolInbox");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.ProtocolOutboxRow", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("ProtocolOutbox");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.RecoveryDecisionRow", b =>
                {
                    b.Property<string>("RecoveryActionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecoverySessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecoveryActionId");

                    b.ToTable("RecoveryDecisions");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.SessionRecoveryRow", b =>
                {
                    b.Property<string>("AgvId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityHash")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CapabilityRevision")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DepartureSafe")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManifestSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingAttemptIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingResultIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolCommit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Readiness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryReportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SafetyHash")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SafetyRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SessionGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AgvId");

                    b.ToTable("SessionRecoveries");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.StationOperationRow", b =>
                {
                    b.Property<string>("SlotOperationAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CommittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("ForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SublotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSlotsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SlotOperationAttemptId");

                    b.ToTable("StationOperations");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.StopClosureRow", b =>
                {
                    b.Property<string>("DemandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DemandId");

                    b.ToTable("StopClosures");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.TransportDemandCompletionRow", b =>
                {
                    b.Property<string>("TransportDemandKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DemandRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransportDemandKey");

                    b.HasIndex("DemandId")
                        .IsUnique();

                    b.ToTable("TransportDemandCompletions");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.UnloadBatchRow", b =>
                {
                    b.Property<string>("UnloadBatchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UnloadBatchId");

                    b.ToTable("UnloadBatches");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.VehicleRecoveryGenerationRow", b =>
                {
                    b.Property<string>("AgvId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AgvId");

                    b.ToTable("VehicleRecoveryGenerations");
                });
#pragma warning restore 612, 618
        }
    }
}
