// <auto-generated />
using System;
using ControlServer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlServer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ControlServerDbContext))]
    [Migration("20260828082910_DurableRiotCreateAttemptAudit")]
    partial class DurableRiotCreateAttemptAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.AcceptedDemandRow", b =>
                {
                    b.Property<string>("DemandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CatalogRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DemandRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HistoryEpoch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LiveMesFieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sublot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportDemandKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValueObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValuePollTraceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueProjectionCommitId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DemandId");

                    b.HasIndex("TransportDemandKey")
                        .IsUnique();

                    b.ToTable("AcceptedDemands");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.AdmissionDecisionSnapshotRow", b =>
                {
                    b.Property<string>("SlotOperationAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AdmissionPolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AdmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Allowed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SlotOperationAttemptId");

                    b.ToTable("AdmissionDecisionSnapshots");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.AdmissionPolicyAuditRow", b =>
                {
                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Version");

                    b.ToTable("AdmissionPolicyAudit");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.AdmissionPolicyStateRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AdmissionPolicyState");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.ConnectionRecoveryRow", b =>
                {
                    b.Property<string>("AgvId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveUnlockSetJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ResumeAuthorized")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SessionGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AgvId");

                    b.ToTable("ConnectionRecoveries");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.ExceptionRecoverySessionRow", b =>
                {
                    b.Property<string>("ExceptionRecoverySessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdministratorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdministratorRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgvId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DemandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ExceptionRecoverySessionId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("ExceptionRecoverySessions");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.HardwareRecoveryRecordRow", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdministratorRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChecksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionRecoverySessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryActionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecordId");

                    b.ToTable("HardwareRecoveryRecords");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.JourneyBacklogRow", b =>
                {
                    b.Property<string>("DemandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DemandCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportDemandKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DemandId");

                    b.HasIndex("TransportDemandKey");

                    b.ToTable("JourneyBacklog");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.JourneyRuntimeRow", b =>
                {
                    b.Property<string>("DemandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgvId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AgvLifecycleGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockReasonCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumedSafetyResultMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumedSublotMessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DispatchGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DispatchZone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedBasketCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GateMovementLegId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GatePlanMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GateStationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GateStationRiotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GateUpperId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GateVehicleBusinessMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GateWorklistMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadCommandMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadSlotOperationAttemptId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PickupMovementLegId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PickupStationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PickupStationRiotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PickupUpperId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PlanRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreDepartureSafetyCheckId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreDepartureSafetyCheckMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteEvidenceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SublotRequestMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSlotsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnloadCommandMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnloadSlotOperationAttemptId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleBusinessMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("VehicleBusinessRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorklistMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("WorklistRevision")
                        .HasColumnType("INTEGER");

                    b.HasKey("DemandId");

                    b.ToTable("JourneyRuntimes");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.MissingPackageRow", b =>
                {
                    b.Property<string>("Package")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Package");

                    b.ToTable("MissingPackages");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.OperationResultRow", b =>
                {
                    b.Property<string>("ResultId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgvId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HistoricalOnly")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OverallOutcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultContentSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotOperationAttemptId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ResultId");

                    b.HasIndex("SlotOperationAttemptId", "ForcedRecoveryGeneration")
                        .IsUnique();

                    b.ToTable("OperationResults");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.OrderIntentRow", b =>
                {
                    b.Property<string>("MovementLegId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AgvLifecycleGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreateAttemptCount")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDispatchArmedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationStationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DispatchAuditVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DispatchGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCreateOutcome")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastCreateOutcomeAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCreateReceiptJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastReconciliationOutcome")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastReconciliationOutcomeAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastReconciliationReceiptJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetStationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpperId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovementLegId");

                    b.HasIndex("CreateAttemptId")
                        .IsUnique()
                        .HasFilter("CreateAttemptId IS NOT NULL");

                    b.HasIndex("UpperId")
                        .IsUnique();

                    b.ToTable("OrderIntents");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.PackageCapacityRuleRow", b =>
                {
                    b.Property<string>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxBoxesPerBasket")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("RuleId");

                    b.HasIndex("Pattern", "MatchType")
                        .IsUnique()
                        .HasFilter("SupersededAt IS NULL");

                    b.ToTable("PackageCapacityRules");

                    b.HasData(
                        new
                        {
                            RuleId = "v1:exact:PDFN5×6-8L(12R)",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 4,
                            Pattern = "PDFN5×6-8L(12R)",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:PDFNWB3.3×3.34",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 4,
                            Pattern = "PDFNWB3.3×3.34",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:PDFNWB5×6",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 4,
                            Pattern = "PDFNWB5×6",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-126",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 8,
                            Pattern = "TO-126",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-220-2L-C",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 8,
                            Pattern = "TO-220-2L-C",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-220-3L",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 8,
                            Pattern = "TO-220-3L",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-220-3L-C(T0.5mm)",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 8,
                            Pattern = "TO-220-3L-C(T0.5mm)",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-220-5L",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 8,
                            Pattern = "TO-220-5L",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-220D-5L",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 8,
                            Pattern = "TO-220D-5L",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-220F",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 8,
                            Pattern = "TO-220F",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-247",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 6,
                            Pattern = "TO-247",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-247-2L-A",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 6,
                            Pattern = "TO-247-2L-A",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-247-4L",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 6,
                            Pattern = "TO-247-4L",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-247A-4L",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 6,
                            Pattern = "TO-247A-4L",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-247B-3L",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 6,
                            Pattern = "TO-247B-3L",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-247Plus-4L",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 6,
                            Pattern = "TO-247Plus-4L",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-251",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 10,
                            Pattern = "TO-251",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-252-2L(4R)",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 5,
                            Pattern = "TO-252-2L(4R)",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-252-2L(6R)",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 4,
                            Pattern = "TO-252-2L(6R)",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-252-2L(8R)",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 4,
                            Pattern = "TO-252-2L(8R)",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-252-5L",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 10,
                            Pattern = "TO-252-5L",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-263-2L",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 8,
                            Pattern = "TO-263-2L",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-263-5L",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 8,
                            Pattern = "TO-263-5L",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-263-7L(2R)",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 6,
                            Pattern = "TO-263-7L(2R)",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-263C-2L",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 8,
                            Pattern = "TO-263C-2L",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-264-3L",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 8,
                            Pattern = "TO-264-3L",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:exact:TO-92",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "exact",
                            MaxBoxesPerBasket = 12,
                            Pattern = "TO-92",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        },
                        new
                        {
                            RuleId = "v1:prefix:TOLL-",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            MatchType = "prefix",
                            MaxBoxesPerBasket = 3,
                            Pattern = "TOLL-",
                            Source = "客户提供花篮容量对照表（2026-07-16迁移）",
                            Version = 1
                        });
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.ProtocolInboxRow", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("ProtocolInbox");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.ProtocolOutboxRow", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FencedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("ProtocolOutbox");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.RecoveryDecisionRow", b =>
                {
                    b.Property<string>("RecoveryActionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecoverySessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecoveryActionId");

                    b.ToTable("RecoveryDecisions");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.RecoveryResultEvidenceRow", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HistoricalOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("RecoveryResultEvidence");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.RecoveryWorkflowRow", b =>
                {
                    b.Property<string>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgvId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandMessageType")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionRecoverySessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HandoffId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotOperationAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowId");

                    b.HasIndex("CommandMessageId")
                        .IsUnique();

                    b.ToTable("RecoveryWorkflows");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.RiotDispatchAuditEventRow", b =>
                {
                    b.Property<string>("AuditEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DispatchGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureCategory")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovementLegId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptClassification")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReceiptObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptOperation")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestSemanticSha256")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ResultPresent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReturnedOrderId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpperId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuditEventId");

                    b.HasIndex("AttemptId");

                    b.HasIndex("MovementLegId", "Sequence")
                        .IsUnique();

                    b.ToTable("RiotDispatchAuditEvents");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.SessionRecoveryRow", b =>
                {
                    b.Property<string>("AgvId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveUnlockSlotsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityHash")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CapabilityRevision")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DepartureSafe")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManifestSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingAttemptIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingResultIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolCommit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProvenRecoveryCheckpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Readiness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryReportId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReportedForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SafetyHash")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SafetyRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SessionGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnsettledSlotOperationAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AgvId");

                    b.ToTable("SessionRecoveries");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.StationOperationRow", b =>
                {
                    b.Property<string>("SlotOperationAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CommittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("ForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SublotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSlotsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SlotOperationAttemptId");

                    b.ToTable("StationOperations");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.StationTaskTypeAdmissionRow", b =>
                {
                    b.Property<string>("StationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskType")
                        .HasColumnType("TEXT");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("StationId", "TaskType");

                    b.ToTable("StationTaskTypeAdmissions");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.StopClosureRow", b =>
                {
                    b.Property<string>("DemandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DemandId");

                    b.ToTable("StopClosures");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.TransportDemandCompletionRow", b =>
                {
                    b.Property<string>("TransportDemandKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DemandRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransportDemandKey");

                    b.HasIndex("DemandId")
                        .IsUnique();

                    b.ToTable("TransportDemandCompletions");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.UnloadBatchRow", b =>
                {
                    b.Property<string>("UnloadBatchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UnloadBatchId");

                    b.ToTable("UnloadBatches");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.VehicleDispatchLeaseRow", b =>
                {
                    b.Property<string>("DemandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DemandId");

                    b.HasIndex("VehicleKey")
                        .IsUnique()
                        .HasFilter("ReleasedAt IS NULL");

                    b.ToTable("VehicleDispatchLeases");
                });

            modelBuilder.Entity("ControlServer.Infrastructure.Persistence.VehicleRecoveryGenerationRow", b =>
                {
                    b.Property<string>("AgvId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ForcedRecoveryGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AgvId");

                    b.ToTable("VehicleRecoveryGenerations");
                });
#pragma warning restore 612, 618
        }
    }
}
